# -*- coding: utf-8 -*-
"""Assignment_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YeycJUOyXxquwp5MnArZEbLkHs6oKLG9

Q.1. What are keywords in python? Using the keyword library, print all the python keywords.
Ans: keywods are special words that cannot be used as identifiers and they
have specific meaning and purpose. ex:- if, for, while etc
import keyword
print(keyword.kwlist)


Q.2. What are the rules to create variables in python?
Ans: Rules to create variable are:
It should not begin with Number
It can have underscores
No special characters can be used

Q.3. What are the standards and conventions followed for the nomenclature
of variables in python to improve code readability and maintainability?
Ans: generally name will specify the scope of that variable
a single underscore mean private variable ex:- _game
a double underscore mean protected variable ex:- __gaming


Q.4. What will happen if a keyword is used as a variable name?
Ans: Error occurs saying SyntaxError: invalid syntax

Q.5. For what purpose def keyword is used?
Ans: def keyword is used to define a function
for ex:-
def play_game():
    print("play")

Q.6. What is the operation of this special character ‘\’?
Ans: it is a continuation character. After using it the line can be
changed to write further expression. this is used when a line of code
expression is large.

Q.7. Give an example of the following conditions:
(i) Homogeneous list
ex:- list1 = ["abu", "talha", "maniyar"]

(ii) Heterogeneous set
ex:- list2 = {"abu", 2, 3, "maniyar"}

(iii) Homogeneous tuple
ex:- (2,4,6,8) or ("im","a","datascientist")

Q.8. Explain the mutable and immutable data types with proper explanation & examples.
Ans: Mutable data types - This is data in which the content can be changed.
example:- list

Immutable data types - This is the data which cannot be modified or changed
if once declared.
example:- tuple

Q.9. Write a code to create the given structure using only for loop.
    *
   ***
  *****
 *******
*********
Ans:
for i in range(5):

  for k in range(4-i):
    print(" ", end="")
  
  for z in range(2*i +1):
    print("*", end="")

  print()

Q.10. Write a code to create the given structure using while loop.
|||||||||
 |||||||
  |||||
   |||
    |
Ans:
i=0
while i<5:
  z=i
  while z:
    print(" ",end="")
    z=z-1

  k=2*i
  while 9-k :
    print("|",end="")
    k=k+1

  i=i+1
  print()
"""